### PR TITLE
Document LPD functionality

### PR DESCRIPTION
**Pull request by itsjeyd**
cf. [OC-4547](https://tasks.opencraft.com/browse/OC-4547)

**Relevant commits**

This PR builds on #11, so only specific commits are relevant:

- f4f4c9be17d1d8b0c12164b7d139cf19571e0de5

**Testing instructions**

None. Just make sure the information added to the README is accurate :)

**Author notes**

I did not add screenshots (yet) since the UI might change based on additional feedback from HGSE.

**Reviewers**

- [x] @tomaszgy

### CODE REVIEW

**Comment by tomaszgy** [comment]
@itsjeyd very good job! I've left a tiny comment, please have a look :) Apart from that:

:+1:

~- [ ] I tested this:~
- [x] I read through the code
~- [ ] I checked for accessibility issues~
- [x] Includes documentation

**Comment by itsjeyd** [comment]
Rebased from f4f4c9be17d1d8b0c12164b7d139cf19571e0de5.

**Comment by itsjeyd** [comment]
Squashed from a31f3a4092790e50ff74fcbc8be027b44729ba5d.

**Comment by itsjeyd** [comment]
@tomaszgy Thanks, as always :), for the review! Merging now.

**Pull request merged**
