### PR TITLE
Address post-delivery feedback, increase logging output

### PR DESCRIPTION
**Pull request by itsjeyd**
cf. [OC-4615](https://tasks.opencraft.com/browse/OC-4615), [OC-4751](https://tasks.opencraft.com/browse/OC-4751)

This PR extends the amount of logging that the LPD does around sending learner profile data to the adaptive engine while improving existing logging behavior (168b6ed7d03d3314bd949bcd63d1be0d906f6dea), and addresses additional feedback from the TLL team (8dcb8582a15ad8f390b28b4aac9a65c2f85e0be5). It also updates some terminology to better differentiate between the concepts of (answer) values and scores (8b1bb86351420582827b93ef7ba7cd39bce6c1d3). Lastly, it brings the documentation up-to-date with additions that we made since #12.

**Related PRs** (increase logging output)

- https://github.com/open-craft/ansible-playbooks/pull/51
- https://github.com/open-craft/ansible-secrets/pull/58

**Test instructions**

1. Update the framing text of a question to include one or more HTML entities.

1. Access the LPD and observe that the HTML entities render correctly.

1. Tail `debug.log` and submit different combinations of answers. Observe that the LPD now:
    - Logs information about learner profile data to transmit to the adaptive engine.
    - Pretty-prints data structures such as lists and dictionaries. 
    - Includes error tracebacks in logs (instead of just briefly mentioning a given error).
    - Explicitly mentions date and time of latest submission (if successful).
    - Logs information about scores to create or update.

**Reviewers**

- [ ] @tomaszgy

### CODE REVIEW

**Comment by tomaszgy** [comment]
@itsjeyd Well done, the things work OK here :)

Although I'm not sure I've seen `pformat` work as intended. It gives the following examples in the logs :

```python
Request data (qualitative answers): [{u'answer_text': u'one,two, three', u'question_id': 24}]

Request data (quantitative answers): [{u'answer_option_value': None, u'answer_option_id': 1, u'question_type': u'likert', u'question_id': 2}, {u'answer_option_value': None, u'answer_option_id': 3, u'question_type': u'likert', u'question_id': 4}, {u'answer_option_custom_input': u'', u'answer_option_value': 5, u'answer_option_id': 6, u'question_type': u'likert', u'question_id': 7}]
```
(I've changed ids when copy-pasting)

Isn't it supposed to add indentation for nested structures?

This is my only objection - could you please check it and update the code if needed? (it may turn out that the current behavior is what we need or that I did something wrong in testing). Thanks!

Other than that, it's good to merge 😃 

👍 (given that `pformat` behavior is checked)
- [x] I tested this:
1. I followed the testing instructions.
- [x] I read through the code
~- [x] I checked for accessibility issues~
- [x] Includes documentation

**Comment by itsjeyd** [comment]
@tomaszgy Thanks for the feedback!

> Although I'm not sure I've seen `pformat` work as intended. It gives the following examples in the logs :
> ...
> Isn't it supposed to add indentation for nested structures?

Yes it is :) That's what I'm seeing on my local machine, I just double-checked. Not sure why you're getting different results. I deployed this branch (as well as changes from https://github.com/open-craft/ansible-playbooks/pull/51) to LPD stage to test logging behavior there, and it's working as expected. See the secret gist that I posted on the ticket for an example and/or check the most recent contents of `/var/log/lpd/debug.log` on LPD stage directly.

**Comment by tomaszgy** [comment]
@itsjeyd 

Thanks, I've just checked `debug.log` on production and the logs have proper formatting so:

LGTM!👍

**Comment by itsjeyd** [comment]
Thanks @tomaszgy! Merging now.

**Pull request merged**
